### ISSUE TITLE
连续多次调试后出现无法保存修改后文件的问题

### ISSUE THREAD

**Issue by CodeBees** [actboy168/vscode-lua-debug#1]
连续多次调试后出现无法保存修改后文件的问题，vscode调试器也无法启动，必须重启vscode才行

##代码

 ``print("lua bit operation ")

axisMask=6

function isForbid(axisMask,idx)

    if idx<1 or idx>64 then
        print("idx cannot be less 1 or bigger than 64")
        return false
    end

    if (1<<(idx-1))&axisMask==0 then
        return false
    else
        return true
    end

end

print(isForbid(axisMask,0));

print(isForbid(axisMask,1));
print(isForbid(axisMask,2));
print(isForbid(axisMask,3));

print(isForbid(axisMask,65));
``

###配置文件

``
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "launch",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/bit.lua",
            "cwd": "${workspaceRoot}",
            "path": "${workspaceRoot}/?.lua",
            "cpath": "${workspaceRoot}/?.dll",
            "arg": [],
            "console": "utf8"
        },
        {
            "name": "attach",
            "type": "lua",
            "request": "attach",
            "stopOnEntry": true,
            "ip": "localhost",
            "port": 4278,
            "sourceMaps": [
                [
                    "./",
                    "${workspaceRoot}"
                ]
            ]
        }            
    ]
}``

**Comment by actboy168** [comment]
无法保存，看起来是vscode的问题。你需要去vscode提一个issues，https://github.com/Microsoft/vscode/issues

**Comment by ly505179140** [comment]
请问下，这个插件只支持纯lua代码调试吗，如果是c++运行lua脚本，可以调试lua代码吗？

**Comment by actboy168** [comment]
@ly505179140，可以用attach模式调试

**Comment by ly505179140** [comment]
@actboy168 你好，能够提供一个说明文档吗，看了你的说明文档，不是很明白应该如何配置attach模式。我的可执行文件运行后，启动vscode调试模式，总是提示“调试适配器进程已意外终止”的错误信息。

**Comment by actboy168** [comment]
@ly505179140，test工程就是一个完整的示例。用默认的配置，选择attach模式，就可以调试test进程。最简单的方法，把test工程搬到你的c++工程里就行

**Comment by ly505179140** [comment]
@actboy168 你好，我的困惑在于我的游戏服务器运行后会将所有的lua文件加载到服务器内存中，如果客户端发送一个消息到服务器后，服务器会调用相应的lua脚本执行游戏逻辑，但是这个lua脚本在vscode里如何去断点调试呢？
你的test工程我运行了，它是在循环调用lua脚本的，按照我的理解，应该是我启动vscode调试模式后，在调试模式下的lua文件中断点，test.exe每次运行lua脚本都会触发vscode里的断点，但实际并不会触发这个断点。
如果需要拥有这样的效果，需要如何配置呢，感谢你的耐心解答。

**Comment by actboy168** [comment]
@ly505179140 
首先你得在客户端有一份和服务端一样lua的代码（这不是必须的，但简单起见，最好先这么来）。用vscode打开客户端的lua代码，简单起见你可以先把stopOnEntry先设为true,这样不用考虑断点，只要路径映射正确attach应该就会停下来。
配置sourceMaps，它是用于映射服务端代码和客户端代码的路径。如果你的服务端代码路径有多个，或者没有和客户端代码的路径保持一致，你可能需要修改它。
此外，如果你的服务端定制了lua代码的加载器，而又没有遵循lua的符号规范，你需要重载custom的path_convert方法，自己实现由lua符号到客户端代码路径的转换。

**Comment by actboy168** [comment]
@ly505179140
用vscode打开test目录，运行test工程，断点可以在任何时候下。这个不需要特别的设置而且应该很简单，没有什么问题。如果test都没有正确执行，我不确定你是遇到了更简单的问题，还是别的什么；不过我想你应该先解决了test的问题，再看我上面的话

**Comment by yingnierxiao** [comment]
问下中debug中转的协议有没有官方的文档可以查询的。想看看具体是怎么实现的代理。

**Comment by actboy168** [comment]
@yingnierxiao vscode本身不需要代理就可以工作，所以不存在代理协议的说法。这点在vscode-lua-debug的readme的最后一段有说明。但是vscode只会连接本地的端口，所以vscode-lua-debug的代理只是为了解决这个问题。
