### ISSUE TITLE
文件名大小写问题？

### ISSUE THREAD

**Issue by nneesshh** [actboy168/vscode-lua-debug#14]
hi，我用 vscode 打开一个文件名区分大小写的lua文件，然后打个断点
然后开始调试，发现 vscode 又打开了一个文件名全部小写的同名文件，断点是断到了，但断点左边的红点提示不会显示

**Comment by actboy168** [comment]
windows本身不支持文件路径区分大小写，所以调试器也没区分大小写

**Comment by actboy168** [comment]
我修改了一下，现在调试器会尊重lua提供的符号的大小写，判定路径相同依然会无视大小写，但不会修改路径本身的大小写。

https://github.com/actboy168/vscode-lua-debug/commit/796996d53ac2bf438ad708e7b060dc57701c585a

**Comment by nneesshh** [comment]
hi actboy168, your project is very helpful, thank you so much to share it

**Comment by nneesshh** [comment]
实测最新版本0.19，此bug已经解决，可以关闭了
