### ISSUE TITLE
遛得飞起，非常好用！

### ISSUE THREAD

**Issue by cliffan** [actboy168/vscode-lua-debug#15]
希望能加入debugger.dll的x64版本

**Comment by actboy168** [comment]
目前debuger.dll是可以编译为x64，并正常工作。你可以自行编译，并通过在lua中加载debuger.dll的方式来调试。
扩展本身，因为debuger-inject.dll目前还不支持x64，所以扩展支持x64还需要一段时间。

**Comment by cliffan** [comment]
谢谢您，我尝试了用vs2017编译x64版本的debugger.dll，刚刚的没毛病。
低版本vs（如vs2015/2013）编译的版本运行起来不正常

**Comment by actboy168** [comment]
低版本的vs目前不支持
