### ISSUE TITLE
vscode正常连接 x64 debugger.dll 后，但调试断点无效

### ISSUE THREAD

**Issue by asunbb** [actboy168/vscode-lua-debug#17]
你好，
    我自己编译了x64的debugger.dll， 启动程序后执行以下lua代码：
```
local dbg = require 'debugger'
dbg.listen('0.0.0.0', 4278)
dbg.start()
```
vscode启动"attach"模式正常连接到目标程序（TCP连接已建立），但无法触发断点进行调试。    
请问，有遇见过这种问题吗？
谢谢

**Comment by actboy168** [comment]
你应该说得更详细一些。

断点无法触发，一般都是因为从`lua符号`到`客户端路径`的转换的某一个环节出问题。

首先调试器支持lua的代码路径的编码ansi或者utf8。默认情况下是ansi，可以通过` dbg.coding('utf8')`的方式来修改。

`lua符号`指的是从`debug.info(0, 'S').source`获取的字符串，它取决于`lua_load`加载代码时所指定的name参数。调试器可以正确地识别遵守lua文档中规定的符号，如果你自己实现了代码加载又没有遵守lua的符号规范，那么你需要实现pathconvert类，帮助调试器将`lua符号`转换为`客户端路径`。pathconvert没有lua接口，你需要用c++实现。

如果你的`lua符号`遵守规范，调试器就可以顺利把`lua符号`转换为`服务端路径`。在远程调试的情境下，`服务端路径`并不等于`客户端路径`，这时你需要配置launch.json里的`sourceMaps`，它可以指定`服务端路径`和`客户端路径`的映射关系。当然你依然可以实现pathconvert类来解决映射的问题。

**Comment by asunbb** [comment]
谢谢，我先尝试从“lua符号”方向来解决问题。
