### ISSUE TITLE
最近更新很频繁,但是你们没发现根本不能用吗,不能触发断点

### ISSUE THREAD

**Issue by zhaobu** [actboy168/vscode-lua-debug#18]
{
            "name": "launch",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": false,
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "path": "${workspaceRoot}/?.lua",
            "cpath": "${workspaceRoot}/?.dll",
            "arg": [],
            "console": "utf8"
        },
这是debug的配置,一直都是可以用的,但是现在已经有2个多星期不能用了,不知道是vscode更新后不能用,还是插件更新不能用,
打的断点根本触发不了.

**Comment by zhaobu** [comment]
说能用的不防把你们的vscode更新到最新版,测试一下就知道了,最新版本是1.21.1

**Comment by actboy168** [comment]
这是因为vscode断点提供的路径和`${file}`不一致(大小写上)
