### ISSUE TITLE
调试 protobuf 反序列化时，鼠标提示信息导致 UI 失去响应

### ISSUE THREAD

**Issue by nneesshh** [actboy168/vscode-lua-debug#19]
当调试 lua protobuf 反序列化过程时，示例代码如下

return function (buffer, pos, pend, message, field_dict)
            local value = field_dict[key]
            if value == nil then
                value = new_default(message)
                field_dict[key] = value
            end
            local size, new_pos
            size, pos = DecodeVarint(buffer, pos)
            new_pos = pos + size
            if new_pos > pend then
                error('Truncated message.')
            end
            return value:_InternalParse(buffer, pos, new_pos)
end

如果不用鼠标经过窗口变量，仍能继续单步调试，但如果鼠标不小心经过了窗口变量，则单步调试按钮失去响应，估计是拉取堆栈时发生了bug，大神有什么解决办法吗？

**Comment by actboy168** [comment]
请提供可复现的例子

**Comment by nneesshh** [comment]
[test_pb.zip](https://github.com/actboy168/vscode-lua-debug/files/1913623/test_pb.zip)
在 “lua\protobuf\decoder.lua” 第 272 行 "size, pos = DecodeVarint(buffer, pos)"打个断点，即可复现。
前面的问题描述有些不准确，应该是“有时候鼠标不经过窗口，调试按钮也可能点击没反应”

**Comment by actboy168** [comment]
在单步调试的状态下，每一步可能会读一次局部变量、上值、可变参数、全局变量的第一层的值。当调试器尝试读一个有`__tostring`元方法的值时，调试器会尝试使用它的返回值作为这个值在调试器内的展示值。

在你的例子中，当调试器读取局部变量`message`并调用它的`__tostring`元方法时，遇到了死循环，所以才会导致这个问题。

当调试器去执行你的代码时它会禁用所有的调试功能，所以你无法得知它发生了死循环。你可以在有问题的地方添加一行`print(message)`，用F11就可以调试`message`的`__tostring`元方法了。

**Comment by nneesshh** [comment]
多谢大神，这个确实有死循环，而且只在消息构造过程中会触发bug形成死循环。

这里本人有个建议，调试器如果依赖了客户本地实现，可能不是一个好主意。平常使用调试器，并不是很希望看到 userdata tostring()以后的值，因此string类型能看到 tostring 后的值就可以了，而userdata 只要提示这是个 userdata 类型即可.
毕竟，调试器本身越强壮越好，如果调试器出了毛病是很让人崩溃的

**Comment by actboy168** [comment]
ok，我已经把`__tostring`改为了`__debugger_tostring`。
