### ISSUE TITLE
如何设置调试设置

### ISSUE THREAD

**Issue by hismile06jf** [actboy168/vscode-lua-debug#24]
我这边是将lua5.3做为lib集成到游戏的exe。
我尝试用launch模式调试exe，配置如下：
"configurations" : [
    {
        "type":"lua",
        "request":"launch"
        "name":"Launch",
        "runtimeExecutable"":"exe path",
        "cwd":"script path",
        "stopOnEntry":true,
    }
]

现在问题是，调试的时候断点的地方提示：未验证的断点。
stopOnEntry是有效的，能够断到脚本代码，但是似乎内存的lua代码没有映射到实际的lua代码。
所以内存看到的lua代码是正确的，但是设置的断点无法断到。

求教如何设置。

**Comment by actboy168** [comment]
你可以先参考这个#17

**Comment by hismile06jf** [comment]
回复的好迅速
我们这边的lua魔改过，应该就是lua符号没按规范走，回头继续魔改试试。
感谢！
