### ISSUE TITLE
启动一个使用lua53.dll的进程失败，能否给一个正确的配置样例

### ISSUE THREAD

**Issue by yuchaoo** [actboy168/vscode-lua-debug#28]
我使用的时候一直启动不成功，提示Launch failed ，配置如下：
"configurations": [
        {
            "name": "launch process",
            "type": "lua",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "stopOnEntry": true,
            "luadll" : "${workspaceRoot}/../external/lib/lua5.3.dll",
            "runtimeExecutable": "${workspaceRoot}/sanguo.win32/Debug/sanguo.win32.exe",
            "consoleCoding": "utf8"
        }
    ]

**Comment by actboy168** [comment]
进程启动失败的原因一般就是你提供的进程本来就启动不了
