### ISSUE TITLE
安装了后没法调试

### ISSUE THREAD

**Issue by yokarno** [actboy168/vscode-lua-debug#3]
最新版本的VSCode，安装了插件后点击调试没反应，原本应该有个配置按钮的也没有，不知道该怎么配置了，Launch.json应该放在哪里？不知道是VSCode的问题还是插件不兼容引起的？

![snip_20170222091958](https://cloud.githubusercontent.com/assets/23699567/23192748/1997489a-f8e0-11e6-9d52-ecd590d37084.png)
![snip_20170222092029](https://cloud.githubusercontent.com/assets/23699567/23192763/31564daa-f8e0-11e6-8a47-e319b87c214d.png)

**Comment by actboy168** [comment]
launch.json在.vscode目录下
看起来是vscode的问题，你应该去这里询问。https://github.com/Microsoft/vscode/issues/

**Comment by CYDjy** [comment]
你要把lua所在的文件夹添加进来，然后才会有配置按钮，新版的需要一个文件去创建.vscode目录

**Comment by yokarno** [comment]
yes, understanded, thanks CYDjy
