### ISSUE TITLE
Can't prompt error message when debug custom runtime executable

### ISSUE THREAD

**Issue by nneesshh** [actboy168/vscode-lua-debug#33]
HI, @actboy168 
My executable "tolua++" just call dofile for "src/toluapp/main.lua".
My debugger version is 4.1
The dbugger will abort silently if  there is some error in my script
See the zip file below:
[test_toluapp.zip](https://github.com/actboy168/vscode-lua-debug/files/2532565/test_toluapp.zip)

PS:
When I use "lua.exe" as "runtimeExecutable", it will prompt error message correctly

**Comment by actboy168** [comment]
The debugger needs a patch to support exception handling.

https://github.com/actboy168/vscode-lua-debug/blob/master/docs/luapatch.md

``` patch
ldblib.c:
@@ -326,6 +326,7 @@
   if (strchr(smask, 'c')) mask |= LUA_MASKCALL;
   if (strchr(smask, 'r')) mask |= LUA_MASKRET;
   if (strchr(smask, 'l')) mask |= LUA_MASKLINE;
+  if (strchr(smask, 'e')) mask |= LUA_MASKEXCEPTION;
   if (count > 0) mask |= LUA_MASKCOUNT;
   return mask;
 }
@@ -339,6 +340,7 @@
   if (mask & LUA_MASKCALL) smask[i++] = 'c';
   if (mask & LUA_MASKRET) smask[i++] = 'r';
   if (mask & LUA_MASKLINE) smask[i++] = 'l';
+  if (mask & LUA_MASKEXCEPTION) smask[i++] = 'e';
   smask[i] = '\0';
   return smask;
 }
ldebug.c:
@@ -638,6 +638,8 @@
 
 
 l_noret luaG_errormsg (lua_State *L) {
+  if (L->hookmask & LUA_MASKEXCEPTION)
+    luaD_hook(L, LUA_HOOKEXCEPTION, -1);
   if (L->errfunc != 0) {  /* is there an error handling function? */
     StkId errfunc = restorestack(L, L->errfunc);
     setobjs2s(L, L->top, L->top - 1);  /* move argument */
lua.h:
@@ -404,15 +404,17 @@
 #define LUA_HOOKLINE	2
 #define LUA_HOOKCOUNT	3
 #define LUA_HOOKTAILCALL 4
+#define LUA_HOOKEXCEPTION 5
 
 
 /*
 ** Event masks
 */
 #define LUA_MASKCALL	(1 << LUA_HOOKCALL)
 #define LUA_MASKRET	(1 << LUA_HOOKRET)
 #define LUA_MASKLINE	(1 << LUA_HOOKLINE)
 #define LUA_MASKCOUNT	(1 << LUA_HOOKCOUNT)
+#define LUA_MASKEXCEPTION	(1 << LUA_HOOKEXCEPTION)
 
 typedef struct lua_Debug lua_Debug;  /* activation record */
 
```

If you don't want to add a patch to lua, you can catch the exception yourself and call debugger::exception.

**Comment by nneesshh** [comment]
Hi @actboy168. Thanks for your nice reply.
I try patching lua according the doc and it works find.
To the second way, call "debugger::exception" through c layer means extra payload.
Can user call "debugger::exception" through lua code?(e.g., The debugger register a "debugger__exception()" function, and user call it in "xpcall" error handler)

**Comment by actboy168** [comment]
First you need to specify the module name of the debugger in launch.json, for example
```
             "internalModule": "debugger"
```
Then you can handle exceptions in lua like this

```
             local dbg = require 'debugger'
             dbg:exception('xpcall', 'ERROR', 0)
```
