### ISSUE TITLE
突然出现调试适配器进程意外终止。

### ISSUE THREAD

**Issue by MidiSmallYue** [actboy168/vscode-lua-debug#38]
在家和公司的电脑突然都出现这个情况，前两天还是好用的。不知道是不是更新导致的呀

**Comment by 8888alex** [comment]
我也遇到相同的情况。
![image](https://user-images.githubusercontent.com/5001484/49848531-6b6c6d80-fe10-11e8-8c3e-9edd266a31a5.png)
原以为是我在尝试别的扩充所导致。尝试各种移除重装后无法排除。
换到另外一台电脑上面开启vscode，看到扩充有更新提示，更新后便出现相同的错误。

**Comment by actboy168** [comment]
287e0bd23b346eafe3b961d0405f834a1ee8a12c 应该已经修复了这个问题
