### ISSUE TITLE
io.read() doesn't work

### ISSUE THREAD

**Issue by oddman621** [actboy168/vscode-lua-debug#41]
![img](https://user-images.githubusercontent.com/15917089/52757187-3b775b80-3047-11e9-9976-2e78940cdb0d.png)

When I try to use io.read() and debug with it, it doesn't work well. My expectation is

what's your name? asd
Hi asd

But result is not. I don't know why the output is like that. Is this the problem, or is there no way to debug with it?

**Comment by actboy168** [comment]
Debug Console is not a terminal.

```json
        {
            "type": "lua",
            "request": "launch",
            "name": "Launch",
            "program": "${file}",
            "console": "externalTerminal",
            "outputCapture": [
            ]
        }
```
You can use this config to get the results you want.

**Comment by oddman621** [comment]
Oh, I see. Thanks for your rapid response.
