### ISSUE TITLE
cocos2d-lua调试

### ISSUE THREAD

**Issue by juebanlin** [actboy168/vscode-lua-debug#5]
请问在这个调试插件在vscode下，如何调试cocos2d-lua的项目，如何加载vscode-debug.dll以及配置地址端口，百度上并没有vscode下调试cocos-lua的相关知识点，是否需要在项目代码中配置，请讲解下，谢谢，

**Comment by actboy168** [comment]
test就是一个很简单的例子，你可以看下
https://github.com/actboy168/vscode-lua-debug/tree/master/test

**Comment by juebanlin** [comment]
我看了，没看到在lua哪里有配置加载dll的代码，test.lua内容为空，c++代码看不懂。。。，还是没搞懂

**Comment by actboy168** [comment]
需要你懂c++才能完成加载的工作

**Comment by juebanlin** [comment]
我记得lua可以加载dll文件，调用函数名或者直接传入IP端口，类似luadebugger的方式，这样也不行？

**Comment by actboy168** [comment]
你可以用luaffi来加载并完成test里所做的事，不过我认为仍然需要你懂c++才能做到

**Comment by juebanlin** [comment]
我以为可以直接这样：
`-- for debugger
local initconnection = require("debugger") 
initconnection('127.0.0.1', 10000 , 'luaidekey')` 我先看看C++代码吧，谢谢
