### ISSUE TITLE
Configure custom Lua debugger

### ISSUE THREAD

**Issue by constructor-igor** [actboy168/vscode-lua-debug#6]
Hi,

I have a custom Lua interpreter S4 (https://github.com/victorliu/S4).
Please, could you add sample of configuration file, how can I debug with help of S4?

thank you,
Igor.

**Comment by actboy168** [comment]
You can see the project.
https://github.com/actboy168/vscode-lua-debug/tree/master/test

**Comment by constructor-igor** [comment]
Where can I define path to S4 interpreter (**S4.exe**)?

**Comment by actboy168** [comment]
You need to add these codes to s4.exe.
```
Create 'vscode::debugger', and then update it.
```

**Comment by constructor-igor** [comment]
Hi,
I take file "launch.json" (see content of the file below).
With help of the file I can debug simple .lua sample, but when I add line ```S = S4.NewSimulation()```, debug cannot execute the line.
My question, if it's possible to config lua debugger to see S4 interpreter (S4.exe). If I am not mistaken, S4 includes a extension of LUA and I need debug the extended language.

```json
{
    "version": "0.2.0",
    "debugServer" : 4278,
    "configurations": [
        {
            "name": "launch",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/main.lua",
            "cwd": "${workspaceRoot}",
            "path": "${workspaceRoot}/?.lua",
            "cpath": "${workspaceRoot}/?.dll",
            "arg": []//,
            //"console": "utf8"
        },
        {
            "name": "attach",
            "type": "lua",
            "request": "attach",
            "stopOnEntry": true,
            "ip": "localhost",
            "port": 4278,
            "sourceMaps": [
                [
                    "./",
                    "${workspaceRoot}"
                ]
            ]
        }
    ]
}
```

![image](https://cloud.githubusercontent.com/assets/1849690/24396901/7160a7f0-13ad-11e7-8a0b-2af70cedb501.png)

**Comment by actboy168** [comment]
Sorry, now does not support custom lua.exe. If you can change s4.exe to s4.dll (just like lua.dll), and then you can use `luadll` parameters to define your s4.dll path.

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "launch",
            "type": "lua",
            "request": "launch",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/main.lua",
            "cwd": "${workspaceRoot}",
            "path": "${workspaceRoot}/?.lua",
            "cpath": "${workspaceRoot}/?.dll",
            "luadll": "${workspaceRoot}/s4.dll",
            "arg": [],
            "console": "utf8"
        },
}
```
